change artifact name

diff --git a/.github/workflows/builder.yml b/.github/workflows/builder.yml
--- a/.github/workflows/builder.yml
+++ b/.github/workflows/builder.yml
@@ -42,7 +42,8 @@ jobs:
       fail-fast: false
       matrix:
         target: [win64, win32]
-        variant: [lgpl-shared, lgpl-shared 4.4, lgpl-shared 5.1, lgpl-shared 6.1, lgpl-shared 7.0]
+        variant: [lgpl-shared]
+        version: [master, 4.4, 5.1, 6.1, 7.0]
     steps:
       - name: Install Latest Docker
         run: |
@@ -61,22 +62,30 @@ jobs:
           sudo rm -rf /opt/hostedtoolcache/CodeQL
           sudo docker image prune --all --force
           OPENH264PRECOMPILED="${{ needs.startup.outputs.openh264ver }}" OPENH264HASH="${{ needs.startup.outputs.openh264hash }}" bash do.bash
+          VER=${{ matrix.version }}
+          if [ "$VER" == "master" ]; then
+            VER=""
+          fi
           cd FFmpeg-Builds
           unset GITHUB_ACTIONS
           unset GITHUB_REPOSITORY
           docker version
-          DOCKER_BUILDKIT=1 NOCLEAN=1 bash ./makeimage.sh ${{ matrix.target }} ${{ matrix.variant }} || echo "Failed"
+          DOCKER_BUILDKIT=1 NOCLEAN=1 bash ./makeimage.sh ${{ matrix.target }} ${{ matrix.variant }} $VER || echo "Failed"
           ls -la .cache/images/base
       - name: Build ffmpeg
         run: |
           cd FFmpeg-Builds
           unset GITHUB_ACTIONS
           unset GITHUB_REPOSITORY
-          bash ./build.sh ${{ matrix.target }} ${{ matrix.variant }}
+          VER=${{ matrix.version }}
+          if [ "$VER" == "master" ]; then
+            VER=""
+          fi
+          bash ./build.sh ${{ matrix.target }} ${{ matrix.variant }} $VER
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: ffmpeg
+          name: artifact-${{ matrix.target }}-${{ matrix.variant }}-${{ matrix.version }}
           path: FFmpeg-Builds/artifacts/*
   create-release:
     needs: [startup, build]
@@ -86,6 +95,10 @@ jobs:
         uses: actions/checkout@v4
       - name: Download artifacts
         uses: actions/download-artifact@v4
+      - name: Merge artifacts
+        run: |
+          mkdir -p ffmpeg
+          mv artifact-*/* ffmpeg/
       - name: Create release
         run: |
           TAG="rel.${{ needs.startup.outputs.date }}"
